import Dexie, { type Table } from 'dexie'
import type {
  UserProfile,
  Program,
  WorkoutSession,
  Exercise,
  CoachMessage,
  WeeklyReview,
  SupplementSchedule,
  SleepLog,
  DailyWellness,
} from '../types'

export class ApexDatabase extends Dexie {
  userProfile!: Table<UserProfile>
  programs!: Table<Program>
  workoutSessions!: Table<WorkoutSession>
  exercises!: Table<Exercise>
  coachMessages!: Table<CoachMessage>
  weeklyReviews!: Table<WeeklyReview>
  supplementSchedules!: Table<SupplementSchedule>
  sleepLogs!: Table<SleepLog>
  dailyWellness!: Table<DailyWellness>

  constructor() {
    super('ApexDB')
    this.version(1).stores({
      userProfile: '++id',
      programs: '++id, isActive, generatedAt',
      workoutSessions: '++id, date, programDayRef',
      exercises: 'id, bodyPart, target, equipment',
      coachMessages: '++id, timestamp, context',
      weeklyReviews: '++id, weekStart',
      supplementSchedules: '++id, supplement',
    })
    this.version(2).stores({
      userProfile: '++id',
      programs: '++id, isActive, generatedAt',
      workoutSessions: '++id, date, programDayRef',
      exercises: 'id, bodyPart, target, equipment',
      coachMessages: '++id, timestamp, context',
      weeklyReviews: '++id, weekStart',
      supplementSchedules: '++id, supplement',
      sleepLogs: '++id, date',
      dailyWellness: '++id, date',
    })
  }
}

export const db = new ApexDatabase()

// ---------------------------------------------------------------------------
// Seed data
// ---------------------------------------------------------------------------

const EXERCISES_SEED: Exercise[] = [
  // ── CHEST ──────────────────────────────────────────────────────────────────
  {
    id: 'barbell-bench-press',
    name: 'Barbell Bench Press',
    nameFr: 'Développé Couché Barre',
    bodyPart: 'chest',
    equipment: 'barbell',
    gifUrl: 'https://v2.exercisedb.io/image/xsYXHZiksGYJgO',
    target: 'pectorals',
    secondaryMuscles: ['triceps', 'delts'],
    instructions: [
      'Allonge-toi sur le banc, dos légèrement cambré, pieds à plat.',
      'Saisie la barre un peu plus large que la largeur des épaules.',
      'Descend la barre jusqu\'au milieu de la poitrine de façon contrôlée.',
      'Pousse la barre vers le haut en contractant les pectoraux.',
      'Verrouille les coudes en haut sans bloquer les articulations.',
    ],
  },
  {
    id: 'incline-barbell-press',
    name: 'Incline Barbell Bench Press',
    nameFr: 'Développé Incliné Barre',
    bodyPart: 'chest',
    equipment: 'barbell',
    gifUrl: 'https://v2.exercisedb.io/image/incline-bench-001',
    target: 'pectorals',
    secondaryMuscles: ['triceps', 'front delts'],
    instructions: [
      'Règle le banc à 30-45 degrés.',
      'Allonge-toi et saisie la barre à largeur d\'épaules.',
      'Descend la barre vers la partie haute de la poitrine.',
      'Pousse vers le haut en gardant les omoplates rétractées.',
    ],
  },
  {
    id: 'push-ups',
    name: 'Push Ups',
    nameFr: 'Pompes',
    bodyPart: 'chest',
    equipment: 'body weight',
    gifUrl: 'https://v2.exercisedb.io/image/push-ups-001',
    target: 'pectorals',
    secondaryMuscles: ['triceps', 'delts', 'core'],
    instructions: [
      'Place les mains légèrement plus larges que les épaules.',
      'Corps en ligne droite de la tête aux talons.',
      'Descend la poitrine vers le sol en fléchissant les coudes.',
      'Pousse pour revenir à la position de départ.',
    ],
  },
  {
    id: 'cable-chest-fly',
    name: 'Cable Chest Fly',
    nameFr: 'Écarté Poulie Câble',
    bodyPart: 'chest',
    equipment: 'cable',
    gifUrl: 'https://v2.exercisedb.io/image/cable-fly-001',
    target: 'pectorals',
    secondaryMuscles: ['biceps'],
    instructions: [
      'Régle les poulies à hauteur des épaules ou plus haut.',
      'Attrape une poignée dans chaque main, un pas en avant.',
      'Garde une légère flexion des coudes tout au long du mouvement.',
      'Ramène les mains ensemble devant toi en arc de cercle.',
      'Contrôle le retour à la position initiale.',
    ],
  },
  // ── BACK ───────────────────────────────────────────────────────────────────
  {
    id: 'pull-ups',
    name: 'Pull Ups',
    nameFr: 'Tractions',
    bodyPart: 'back',
    equipment: 'body weight',
    gifUrl: 'https://v2.exercisedb.io/image/pull-ups-001',
    target: 'lats',
    secondaryMuscles: ['biceps', 'rear delts', 'rhomboids'],
    instructions: [
      'Saisie la barre en pronation, un peu plus large que les épaules.',
      'Pars d\'un hang mort, bras tendus.',
      'Tire le menton au-dessus de la barre en engageant les dorsaux.',
      'Descend de façon contrôlée jusqu\'à l\'extension complète.',
    ],
  },
  {
    id: 'barbell-row',
    name: 'Barbell Bent-Over Row',
    nameFr: 'Rowing Barre Penché',
    bodyPart: 'back',
    equipment: 'barbell',
    gifUrl: 'https://v2.exercisedb.io/image/barbell-row-001',
    target: 'lats',
    secondaryMuscles: ['rhomboids', 'biceps', 'rear delts', 'traps'],
    instructions: [
      'Incline le buste à 45° en gardant le dos droit.',
      'Saisie la barre en pronation à largeur d\'épaules.',
      'Tire la barre vers le bas de l\'abdomen en serrant les omoplates.',
      'Descend la barre de façon contrôlée.',
    ],
  },
  {
    id: 'lat-pulldown',
    name: 'Lat Pulldown',
    nameFr: 'Tirage Vertical Poulie Haute',
    bodyPart: 'back',
    equipment: 'cable',
    gifUrl: 'https://v2.exercisedb.io/image/lat-pulldown-001',
    target: 'lats',
    secondaryMuscles: ['biceps', 'rear delts'],
    instructions: [
      'Assieds-toi face à la machine, cuisses sous les appuis.',
      'Saisie la barre en pronation large.',
      'Tire la barre vers le haut de la poitrine en rétractant les omoplates.',
      'Contrôle la remontée lentement.',
    ],
  },
  {
    id: 'cable-seated-row',
    name: 'Cable Seated Row',
    nameFr: 'Rowing Assis Câble',
    bodyPart: 'back',
    equipment: 'cable',
    gifUrl: 'https://v2.exercisedb.io/image/cable-row-001',
    target: 'lats',
    secondaryMuscles: ['rhomboids', 'biceps', 'traps'],
    instructions: [
      'Assieds-toi sur le banc, pieds sur les appuis, genoux légèrement fléchis.',
      'Saisie la poignée en prise neutre.',
      'Tire la poignée vers le nombril en gardant le dos droit.',
      'Serre les omoplates en position haute.',
      'Reviens lentement à la position initiale.',
    ],
  },
  // ── LEGS ───────────────────────────────────────────────────────────────────
  {
    id: 'barbell-squat',
    name: 'Barbell Back Squat',
    nameFr: 'Squat Barre Haute',
    bodyPart: 'upper legs',
    equipment: 'barbell',
    gifUrl: 'https://v2.exercisedb.io/image/barbell-squat-001',
    target: 'quads',
    secondaryMuscles: ['glutes', 'hamstrings', 'core', 'erectors'],
    instructions: [
      'Place la barre sur les trapèzes, légèrement sous les vertèbres cervicales.',
      'Pieds à largeur des épaules ou légèrement plus, orteils vers l\'extérieur.',
      'Descend en poussant les genoux vers l\'extérieur, hanche en dessous des genoux.',
      'Remonte en poussant le sol avec les talons.',
    ],
  },
  {
    id: 'leg-press',
    name: 'Leg Press',
    nameFr: 'Presse à Cuisses',
    bodyPart: 'upper legs',
    equipment: 'machine',
    gifUrl: 'https://v2.exercisedb.io/image/leg-press-001',
    target: 'quads',
    secondaryMuscles: ['glutes', 'hamstrings'],
    instructions: [
      'Assieds-toi dans la machine, dos plaqué contre le dossier.',
      'Place les pieds à largeur des épaules sur la plateforme.',
      'Libère les sécurités et descend lentement la plateforme.',
      'Pousse avec les talons jusqu\'à l\'extension quasi-complète.',
      'Ne verrouille pas les genoux en haut.',
    ],
  },
  {
    id: 'romanian-deadlift',
    name: 'Romanian Deadlift',
    nameFr: 'Soulevé de Terre Roumain',
    bodyPart: 'upper legs',
    equipment: 'barbell',
    gifUrl: 'https://v2.exercisedb.io/image/rdl-001',
    target: 'hamstrings',
    secondaryMuscles: ['glutes', 'erectors', 'lats'],
    instructions: [
      'Tiens la barre devant toi, épaules en arrière.',
      'Fléchis légèrement les genoux, pousse les hanches vers l\'arrière.',
      'Descend la barre le long des jambes en gardant le dos droit.',
      'Remonte en contractant les fessiers et les ischio-jambiers.',
    ],
  },
  {
    id: 'leg-curl-machine',
    name: 'Lying Leg Curl',
    nameFr: 'Leg Curl Allongé',
    bodyPart: 'upper legs',
    equipment: 'machine',
    gifUrl: 'https://v2.exercisedb.io/image/leg-curl-001',
    target: 'hamstrings',
    secondaryMuscles: ['calves'],
    instructions: [
      'Allonge-toi sur la machine ventre contre le banc.',
      'Place les chevilles sous le coussin.',
      'Fléchis les genoux pour ramener les talons vers les fessiers.',
      'Contrôle la descente lentement.',
    ],
  },
  {
    id: 'leg-extension-machine',
    name: 'Leg Extension',
    nameFr: 'Extension Jambe Machine',
    bodyPart: 'upper legs',
    equipment: 'machine',
    gifUrl: 'https://v2.exercisedb.io/image/leg-ext-001',
    target: 'quads',
    secondaryMuscles: [],
    instructions: [
      'Assieds-toi sur la machine, dos contre le dossier.',
      'Place les chevilles sous le coussin.',
      'Étends les jambes jusqu\'à l\'horizontale en contractant les quadriceps.',
      'Descend lentement et de façon contrôlée.',
    ],
  },
  {
    id: 'hip-thrust',
    name: 'Barbell Hip Thrust',
    nameFr: 'Hip Thrust Barre',
    bodyPart: 'upper legs',
    equipment: 'barbell',
    gifUrl: 'https://v2.exercisedb.io/image/hip-thrust-001',
    target: 'glutes',
    secondaryMuscles: ['hamstrings', 'core'],
    instructions: [
      'Appuie le haut du dos contre un banc, barre sur les hanches.',
      'Pieds à plat sur le sol, genoux fléchis à 90°.',
      'Pousse les hanches vers le haut en contractant les fessiers.',
      'Redescend lentement sans laisser les hanches toucher le sol.',
    ],
  },
  {
    id: 'bulgarian-split-squat',
    name: 'Bulgarian Split Squat',
    nameFr: 'Squat Bulgare',
    bodyPart: 'upper legs',
    equipment: 'barbell',
    gifUrl: 'https://v2.exercisedb.io/image/bss-001',
    target: 'quads',
    secondaryMuscles: ['glutes', 'hamstrings'],
    instructions: [
      'Place le pied arrière sur un banc derrière toi.',
      'Pied avant suffisamment en avant pour que le genou avant ne dépasse pas les orteils.',
      'Descend jusqu\'à ce que la cuisse avant soit parallèle au sol.',
      'Remonte en poussant sur le talon du pied avant.',
    ],
  },
  // ── SHOULDERS ──────────────────────────────────────────────────────────────
  {
    id: 'overhead-press',
    name: 'Barbell Overhead Press',
    nameFr: 'Développé Militaire Barre',
    bodyPart: 'shoulders',
    equipment: 'barbell',
    gifUrl: 'https://v2.exercisedb.io/image/ohp-001',
    target: 'delts',
    secondaryMuscles: ['triceps', 'traps', 'core'],
    instructions: [
      'Tiens la barre à hauteur d\'épaules, prise légèrement plus large que les épaules.',
      'Pousse la barre directement vers le haut en rentrant légèrement la tête.',
      'Étends les bras complètement sans verrouiller les coudes.',
      'Redescend lentement jusqu\'aux clavicules.',
    ],
  },
  {
    id: 'dumbbell-lateral-raise',
    name: 'Dumbbell Lateral Raise',
    nameFr: 'Élévation Latérale Haltères',
    bodyPart: 'shoulders',
    equipment: 'dumbbell',
    gifUrl: 'https://v2.exercisedb.io/image/lat-raise-001',
    target: 'delts',
    secondaryMuscles: ['traps'],
    instructions: [
      'Tiens les haltères de chaque côté du corps.',
      'Lève les bras sur les côtés jusqu\'à hauteur des épaules.',
      'Garde un léger angle dans les coudes, pouces légèrement vers le bas.',
      'Descend lentement et de façon contrôlée.',
    ],
  },
  {
    id: 'cable-face-pull',
    name: 'Cable Face Pull',
    nameFr: 'Face Pull Câble',
    bodyPart: 'shoulders',
    equipment: 'cable',
    gifUrl: 'https://v2.exercisedb.io/image/face-pull-001',
    target: 'delts',
    secondaryMuscles: ['rear delts', 'rhomboids', 'rotator cuff'],
    instructions: [
      'Règle la poulie à hauteur des yeux avec une corde.',
      'Recule de quelques pas, bras tendus vers la poulie.',
      'Tire la corde vers le visage en écartant les mains vers l\'extérieur.',
      'Serre les épaules en arrière en position finale.',
      'Reviens lentement.',
    ],
  },
  // ── ARMS ───────────────────────────────────────────────────────────────────
  {
    id: 'barbell-curl',
    name: 'Barbell Bicep Curl',
    nameFr: 'Curl Barre Biceps',
    bodyPart: 'upper arms',
    equipment: 'barbell',
    gifUrl: 'https://v2.exercisedb.io/image/barbell-curl-001',
    target: 'biceps',
    secondaryMuscles: ['brachialis', 'forearms'],
    instructions: [
      'Tiens la barre en supination, bras le long du corps.',
      'Coudes plaqués contre le buste.',
      'Fléchis les coudes pour amener la barre vers les épaules.',
      'Descend lentement et de façon contrôlée.',
    ],
  },
  {
    id: 'hammer-curl',
    name: 'Dumbbell Hammer Curl',
    nameFr: 'Curl Marteau Haltère',
    bodyPart: 'upper arms',
    equipment: 'dumbbell',
    gifUrl: 'https://v2.exercisedb.io/image/hammer-curl-001',
    target: 'biceps',
    secondaryMuscles: ['brachialis', 'brachioradialis'],
    instructions: [
      'Tiens les haltères en prise neutre (pouce vers le haut).',
      'Coudes près du corps.',
      'Fléchis les coudes en montant les haltères vers les épaules.',
      'Contrôle la descente.',
    ],
  },
  {
    id: 'incline-dumbbell-curl',
    name: 'Incline Dumbbell Curl',
    nameFr: 'Curl Haltère Incliné',
    bodyPart: 'upper arms',
    equipment: 'dumbbell',
    gifUrl: 'https://v2.exercisedb.io/image/incline-curl-001',
    target: 'biceps',
    secondaryMuscles: ['brachialis'],
    instructions: [
      'Allonge-toi sur un banc incliné à 60-70°.',
      'Laisse les bras pendre librement en supination.',
      'Fléchis les coudes en amenant les haltères vers les épaules.',
      'Descend lentement pour maximiser l\'étirement.',
    ],
  },
  {
    id: 'cable-tricep-pushdown',
    name: 'Cable Tricep Pushdown',
    nameFr: 'Extension Triceps Câble',
    bodyPart: 'upper arms',
    equipment: 'cable',
    gifUrl: 'https://v2.exercisedb.io/image/tricep-pushdown-001',
    target: 'triceps',
    secondaryMuscles: [],
    instructions: [
      'Tiens la corde ou la barre en V à la poulie haute.',
      'Coudes plaqués contre le buste.',
      'Étends les avant-bras vers le bas en contractant les triceps.',
      'Contrôle la remontée sans bouger les coudes.',
    ],
  },
  {
    id: 'skull-crusher',
    name: 'EZ Bar Skull Crusher',
    nameFr: 'Barre Front (Skull Crusher)',
    bodyPart: 'upper arms',
    equipment: 'barbell',
    gifUrl: 'https://v2.exercisedb.io/image/skull-crusher-001',
    target: 'triceps',
    secondaryMuscles: [],
    instructions: [
      'Allonge-toi sur un banc plat, tiens la barre EZ au-dessus de la tête.',
      'Bras verticaux, coudes pointant vers le plafond.',
      'Fléchis les coudes pour descendre la barre vers le front.',
      'Étends les bras pour revenir à la position de départ.',
    ],
  },
  {
    id: 'dips',
    name: 'Tricep Dips',
    nameFr: 'Dips Triceps',
    bodyPart: 'upper arms',
    equipment: 'body weight',
    gifUrl: 'https://v2.exercisedb.io/image/dips-001',
    target: 'triceps',
    secondaryMuscles: ['chest', 'delts'],
    instructions: [
      'Tiens les barres parallèles, bras tendus, corps vertical.',
      'Descend lentement en fléchissant les coudes.',
      'Descend jusqu\'à ce que les coudes forment un angle de 90°.',
      'Remonte en poussant vers le haut.',
    ],
  },
  // ── CORE ───────────────────────────────────────────────────────────────────
  {
    id: 'plank',
    name: 'Plank',
    nameFr: 'Gainage Planche',
    bodyPart: 'waist',
    equipment: 'body weight',
    gifUrl: 'https://v2.exercisedb.io/image/plank-001',
    target: 'abs',
    secondaryMuscles: ['core', 'glutes', 'back'],
    instructions: [
      'Appuie-toi sur les avant-bras et les orteils.',
      'Corps en ligne droite de la tête aux talons.',
      'Contracte le ventre et les fessiers.',
      'Garde la position en respirant régulièrement.',
    ],
  },
  {
    id: 'cable-crunch',
    name: 'Cable Crunch',
    nameFr: 'Crunch Câble',
    bodyPart: 'waist',
    equipment: 'cable',
    gifUrl: 'https://v2.exercisedb.io/image/cable-crunch-001',
    target: 'abs',
    secondaryMuscles: ['obliques'],
    instructions: [
      'Agenouille-toi face à la poulie haute avec une corde.',
      'Tiens la corde de chaque côté de la tête.',
      'Fléchis le buste vers le bas en contractant les abdominaux.',
      'Remonte lentement.',
    ],
  },
  {
    id: 'hanging-leg-raise',
    name: 'Hanging Leg Raise',
    nameFr: 'Relevé de Jambes Suspendu',
    bodyPart: 'waist',
    equipment: 'body weight',
    gifUrl: 'https://v2.exercisedb.io/image/hanging-lr-001',
    target: 'abs',
    secondaryMuscles: ['hip flexors', 'obliques'],
    instructions: [
      'Suspends-toi à une barre, bras tendus.',
      'Garde les jambes tendues ou légèrement fléchies.',
      'Lève les jambes jusqu\'à l\'horizontale ou plus haut.',
      'Descend lentement sans balancer.',
    ],
  },
  // ── BACK (additional) ──────────────────────────────────────────────────────
  {
    id: 'conventional-deadlift',
    name: 'Conventional Deadlift',
    nameFr: 'Soulevé de Terre Conventionnel',
    bodyPart: 'back',
    equipment: 'barbell',
    gifUrl: 'https://v2.exercisedb.io/image/deadlift-001',
    target: 'erector spinae',
    secondaryMuscles: ['glutes', 'hamstrings', 'lats', 'traps', 'quads'],
    instructions: [
      'Pieds à largeur des hanches, barre au-dessus des mi-pieds.',
      'Saisie la barre un peu plus large que les épaules.',
      'Dos droit, hanches plus basses que les épaules.',
      'Pousse le sol vers le bas pour initier le mouvement.',
      'Barre plaquée contre les jambes tout au long du mouvement.',
      'Hanche et genoux s\'étendent simultanément.',
    ],
  },
]

export async function seedExercises(): Promise<void> {
  const count = await db.exercises.count()
  if (count > 0) return // already seeded
  await db.exercises.bulkPut(EXERCISES_SEED)
}
